### ISSUE TITLE
svg file, right thumbinal but wrong svg

### ISSUE THREAD

**Issue by alessandriLuca** [gladkia/igvR#13]
Hi, i would like to compliment on this work. Is great! definetly better then the normal igv browser. Im planning to use it a lot. 
I have some trouble on svg saving from both the browser and from the code it give me the same results. So apparently when i load a bedgraph with negative value they are displayed on the browser, then i save everything on svg and here is the problem, positive value of bedgraph are fine, negative just disappear. Another funny thing is that in the thumbinal of the svg i can definetly see the negative value. Here is an example of svg [file](https://file.io/3H1wwhn3LahZ)
Also here are the version of the libraries installed in my R environment.
As browser im using firefox 88.0 (64-bit) on Kubuntu 20.04.2 LTS. (I also tried Chromium but i have the same issue)

R version 3.6.3 (2020-02-29)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 20.04.2 LTS

Matrix products: default
BLAS:   /usr/lib/x86_64-linux-gnu/blas/libblas.so.3.9.0
LAPACK: /usr/lib/x86_64-linux-gnu/lapack/liblapack.so.3.9.0

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C              
 [3] LC_TIME=it_IT.UTF-8        LC_COLLATE=en_US.UTF-8    
 [5] LC_MONETARY=it_IT.UTF-8    LC_MESSAGES=en_US.UTF-8   
 [7] LC_PAPER=it_IT.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=it_IT.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] parallel  stats4    stats     graphics  grDevices utils     datasets 
[8] methods   base     

other attached packages:
 [1] rtracklayer_1.46.0          AnnotationHub_2.18.0       
 [3] BiocFileCache_1.10.2        dbplyr_2.1.1               
 [5] VariantAnnotation_1.32.0    igvR_1.11.2                
 [7] BrowserViz_2.12.0           httpuv_1.6.0               
 [9] jsonlite_1.7.2              GenomicAlignments_1.22.1   
[11] Rsamtools_2.2.3             Biostrings_2.54.0          
[13] XVector_0.26.0              SummarizedExperiment_1.16.1
[15] DelayedArray_0.12.3         BiocParallel_1.20.1        
[17] matrixStats_0.58.0          Biobase_2.46.0             
[19] GenomicRanges_1.38.0        GenomeInfoDb_1.22.1        
[21] IRanges_2.20.2              S4Vectors_0.24.4           
[23] BiocGenerics_0.32.0        

loaded via a namespace (and not attached):
 [1] httr_1.4.2                    bit64_4.0.5                  
 [3] shiny_1.6.0                   assertthat_0.2.1             
 [5] interactiveDisplayBase_1.24.0 askpass_1.1                  
 [7] BiocManager_1.30.12           blob_1.2.1                   
 [9] BSgenome_1.54.0               GenomeInfoDbData_1.2.2       
[11] yaml_2.2.1                    progress_1.2.2               
[13] BiocVersion_3.10.1            pillar_1.6.0                 
[15] RSQLite_2.2.7                 lattice_0.20-44              
[17] glue_1.4.2                    digest_0.6.27                
[19] RColorBrewer_1.1-2            promises_1.2.0.1             
[21] htmltools_0.5.1.1             Matrix_1.3-3                 
[23] XML_3.99-0.3                  pkgconfig_2.0.3              
[25] biomaRt_2.42.1                zlibbioc_1.32.0              
[27] xtable_1.8-4                  purrr_0.3.4                  
[29] later_1.2.0                   tibble_3.1.1                 
[31] openssl_1.4.4                 generics_0.1.0               
[33] ellipsis_0.3.2                cachem_1.0.4                 
[35] GenomicFeatures_1.38.2        mime_0.10                    
[37] splitstackshape_1.4.8         magrittr_2.0.1               
[39] crayon_1.4.1                  memoise_2.0.0                
[41] fansi_0.4.2                   tools_3.6.3                  
[43] data.table_1.14.0             prettyunits_1.1.1            
[45] hms_1.0.0                     lifecycle_1.0.0              
[47] stringr_1.4.0                 AnnotationDbi_1.48.0         
[49] compiler_3.6.3                rlang_0.4.11                 
[51] MotifDb_1.28.0                grid_3.6.3                   
[53] RCurl_1.98-1.3                rappdirs_0.3.3               
[55] bitops_1.0-7                  DBI_1.1.1                    
[57] curl_4.3.1                    R6_2.5.0                     
[59] seqLogo_1.52.0                dplyr_1.0.5                  
[61] fastmap_1.1.0                 bit_4.0.4                    
[63] utf8_1.2.1                    stringi_1.5.3                
[65] Rcpp_1.0.6                    vctrs_0.3.8                  
[67] tidyselect_1.1.1 

Thank you 

Best

**Comment by paul-shannon** [comment]
Traveling now, will look on Saturday. 
Thanks for the report!

**Comment by paul-shannon** [comment]
I had hoped to take a look at this during a brief stay in Boulder, but failed to do so.

I will be home on May 16th, and promise to look at this then.

 - Paul

**Comment by alessandriLuca** [comment]
Hi, no worries, right now I solved with automatic screenshot xD so i can use it anyway! Take your time and thanks again!

**Comment by alessandriLuca** [comment]
I Also have another question, is there any way in which i can disable track labels? From the browser i can unselect the option but i wasnt able to find anything related to that in the igvR code. Thank you again 

Best

Luca

**Comment by paul-shannon** [comment]
@alessandriLuca 
I upgraded (this is long overdue) to igv.js 2.8.2, and igvR::getSvg() now works better.   But still not quite right.

See new issue at github igv.js[svg of +/- bedgraph lacks the zero line (chrom, safari, firefox) #1332](https://github.com/igvteam/igv.js/issues/1332).

I will update again once Jim Robinson solves this problem - or shows me that it is my error :) 

Many thanks for the bug report!

**Comment by alessandriLuca** [comment]
@paul-shannon many thanks for your work! Can i leave this open as a remind for when it will be totally fixed? 

Thank you again and, again congratulation for the great job ;) is super usefull!! 

Best

Luca

**Comment by paul-shannon** [comment]
Yes, please leave it open.

Programmatic show/hide track labels goes in today.

Great to have your reports and requests!

 -  Paul

**Comment by paul-shannon** [comment]
Just verified that ```showTrackLabels(igv, TRUE|FALSE)``` works, so closing this belatedly.
